### ISSUE TITLE
Note-it overflow on small size

### ISSUE THREAD

**Issue by rawatdev** [MuhametSmaili/note-it#82]
On edge browser, when, we use Note-it on fullscreen it works very well. But on small size some buttons are goes out of viewing window.

![image](https://user-images.githubusercontent.com/39383758/184135027-ba815453-81d2-426d-bb23-2818dc132cd6.png)

**Comment by MuhametSmaili** [comment]
[Our chrome extension has a minimum width and height.
](https://github.com/MuhametSmaili/note-it/blob/main/src/popup/popup.tsx#:~:text=%3Cdiv%20style%3D%7B%7B%20width%3A%20%27768px%27%2C%20minHeight%3A%20%27550px%27%20%7D%7D)
This maybe will change in the future, but now it is not in our plans.
 We do not see the current design as usable for a device that has a lower screen resolution than 700px. 

This extension should work just fine in the chrome extension, also you have the option to open it in your windows so you can move to the place you want.
Having the static width/height does not mean you can not make it a smaller window, but the scrollbars will appear.

Feel free to re-open the issue and discuss more. 

For reopening the issue please write/tell me how we can reproduce the error/bug because in chrome it works fine, I have tested multiple times.

Thanks in advance
